<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine.Base\Engine.Base.csproj" />
    <ProjectReference Include="..\Engine.Core\Engine.Core.csproj" />
  </ItemGroup>

</Project>
